# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI - Continuous Integration

on: ['push', 'pull_request']

jobs:
  run-unit-tests:
    name: run unit tests
    runs-on: ubuntu-latest
    container: node:lts

    services:
      database:
        image: mysql
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: password

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install dependencies
        uses: bahmutov/npm-install@v1

      - name: run unit tests
        run: npm run test:unit


